### ISSUE TITLE
GL_QUAD_STRIP broken

### ISSUE THREAD

**Issue by claudeha** [emscripten-ports/regal#6]
With incoming regal port (version 4) I get this printout in the Firefox console and my shape isn't drawn:

    Error: WebGL warning: drawElements: Index buffer too small.

Reproducing test case:

    // emcc -s USE_SDL=2 -s USE_REGAL=1 -o quadstrip.html quadstrip.c -lGL
    // gcc -o quadstrip quadstrip.c -lGL -lSDL2
    
    #ifdef __EMSCRIPTEN__
    #include <emscripten.h>
    #include <GL/Regal.h>
    #else
    #include <GL/gl.h>
    #endif
    #include <SDL2/SDL.h>
    
    SDL_Window *window = 0;
    SDL_GLContext context;
    
    void main1(void)
    {
      glClear(GL_COLOR_BUFFER_BIT);
    
      glBegin(GL_QUAD_STRIP);
      glVertex2f(-0.5, -0.5);
      glVertex2f( 0.5, -0.5);
      glVertex2f( 0.5,  0.5);
      glVertex2f(-0.5,  0.5);
      glVertex2f(-0.5,  1.5);
      glVertex2f( 0.5,  1.5);
      glEnd();
    
      SDL_GL_SwapWindow(window);
    }
    
    int main(int argc, char **argv)
    {
      SDL_Init(SDL_INIT_VIDEO);
      window = SDL_CreateWindow("GL_QUAD_STRIP", 0, 0, 640, 480, SDL_WINDOW_OPENGL);
      context = SDL_GL_CreateContext(window);
      SDL_GL_MakeCurrent(window, context);
    #ifdef __EMSCRIPTEN__
      RegalMakeCurrent((void *) 1);
    #endif
    
      glDisable(GL_DEPTH_TEST);
      glClearColor(0, 0, 1, 1);
      glColor4f(1, 0, 0, 1);
    
    #ifdef __EMSCRIPTEN__
      emscripten_set_main_loop(main1, 0, 1);
    #else
      while(1) main1();
    #endif
      return 0;
    }

With logging enabled:

    ...
    app      | glEnable (GL_LOG_DRIVER_REGAL)
    app      | glEnable (GL_LOG_INTERNAL_REGAL)
    app      | glEnable (GL_LOG_HTTP_REGAL)
    app      | glDisable (GL_DEPTH_TEST)
    internal | Regal::Ppa::Disable  GL_DEPTH_TEST
    internal | Regal::Iff::State::SetEnable false GL_DEPTH_TEST
    driver   | glDisable (GL_DEPTH_TEST)
    app      | glClearColor (0, 0, 1, 1)
    driver   | glClearColor (0, 0, 1, 1)
    app      | glColor4f (1, 0, 0, 1)
    app      | glClear (GL_COLOR_BUFFER_BIT)
    driver   | glClear (GL_COLOR_BUFFER_BIT)
    app      | glBegin (GL_QUAD_STRIP)
    driver   |   glBindBuffer (GL_ARRAY_BUFFER, 2)
    driver   |   glBindBuffer (GL_ELEMENT_ARRAY_BUFFER, 3)
    driver   |   glEnableVertexAttribArray (0)
    driver   |   glVertexAttribPointer (0, 4, GL_FLOAT, GL_FALSE, 128, 00000000)
    driver   |   glEnableVertexAttribArray (1)
    driver   |   glVertexAttribPointer (1, 4, GL_FLOAT, GL_FALSE, 128, 00000010)
    driver   |   glEnableVertexAttribArray (2)
    driver   |   glVertexAttribPointer (2, 4, GL_FLOAT, GL_FALSE, 128, 00000020)
    driver   |   glEnableVertexAttribArray (3)
    driver   |   glVertexAttribPointer (3, 4, GL_FLOAT, GL_FALSE, 128, 00000030)
    driver   |   glEnableVertexAttribArray (4)
    driver   |   glVertexAttribPointer (4, 4, GL_FLOAT, GL_FALSE, 128, 00000040)
    driver   |   glEnableVertexAttribArray (5)
    driver   |   glVertexAttribPointer (5, 4, GL_FLOAT, GL_FALSE, 128, 00000050)
    driver   |   glEnableVertexAttribArray (6)
    driver   |   glVertexAttribPointer (6, 4, GL_FLOAT, GL_FALSE, 128, 00000060)
    driver   |   glEnableVertexAttribArray (7)
    driver   |   glVertexAttribPointer (7, 4, GL_FLOAT, GL_FALSE, 128, 00000070)
    internal |   Regal::Iff::UseFixedFunctionProgram 00547ad8
    internal |   Iff::State::Process ()
    internal |   Iff::State::Process ()
    internal |   Regal::Iff::GenerateVertexShaderSource 00558458
    internal |   Regal::Iff::Program::Shader ()
    driver   |   glCreateShader (GL_VERTEX_SHADER) returned 4
    driver   | %03i   glShaderSource (4, 1, [ "#version 100
    driver   | %03i   glShaderSource // program number 1
    driver   | %03i   glShaderSource #define in attribute
    driver   | %03i   glShaderSource #define out varying
    driver   | %03i   glShaderSource #define FLAT  
    driver   | %03i   glShaderSource precision highp float;
    driver   | %03i   glShaderSource uniform mat4 rglModelViewMatrix;
    driver   | %03i   glShaderSource uniform mat4 rglProjectionMatrix;
    driver   | %03i   glShaderSource in vec4 rglVertex;
    driver   | %03i   glShaderSource in vec4 rglColor;
    driver   | %03i   glShaderSource FLAT out vec4 rglFrontColor;
    driver   | %03i   glShaderSource #define gl_TexCoord rglTEXCOORD
    driver   | %03i   glShaderSource out vec4 rglTEXCOORD[4];
    driver   | %03i   glShaderSource void main() {
    driver   | %03i   glShaderSource     gl_Position = rglProjectionMatrix * rglModelViewMatrix * rglVertex;
    driver   | %03i   glShaderSource     rglFrontColor = rglColor;
    driver   | %03i   glShaderSource     rglFrontColor = clamp( rglFrontColor, 0.0, 1.0 );
    driver   | %03i   glShaderSource }
    driver   | %03i   glShaderSource " ], [ 474 ])
    driver   |   glCompileShader (4)
    internal |   Iff::State::Process ()
    internal |   Regal::Iff::GenerateFragmentShaderSource 00558458
    internal |   Regal::Iff::Program::Shader ()
    driver   |   glCreateShader (GL_FRAGMENT_SHADER) returned 5
    driver   | %03i   glShaderSource (5, 1, [ "#version 100
    driver   | %03i   glShaderSource // program number 1
    driver   | %03i   glShaderSource #define in varying
    driver   | %03i   glShaderSource #define rglFragColor gl_FragColor
    driver   | %03i   glShaderSource #define FLAT  
    driver   | %03i   glShaderSource precision highp float;
    driver   | %03i   glShaderSource FLAT in vec4 rglFrontColor;
    driver   | %03i   glShaderSource #define gl_TexCoord rglTEXCOORD
    driver   | %03i   glShaderSource in vec4 rglTEXCOORD[4];
    driver   | %03i   glShaderSource void main() {
    driver   | %03i   glShaderSource     vec4 p = rglFrontColor;
    driver   | %03i   glShaderSource     rglFragColor = p;
    driver   | %03i   glShaderSource }
    driver   | %03i   glShaderSource " ], [ 274 ])
    driver   |   glCompileShader (5)
    internal |   Regal::Iff::Program::Init ()
    driver   |   glCreateProgram () returned 6
    driver   |   glAttachShader (6, 4)
    driver   |   glAttachShader (6, 5)
    internal |   Regal::Iff::Program::Attribs ()
    driver   |   glBindAttribLocation (6, 0, "rglVertex")
    driver   |   glBindAttribLocation (6, 1, "rglColor")
    driver   |   glLinkProgram (6)
    driver   |   glUseProgram (6)
    driver   |   glIsProgram (6) returned GL_TRUE
    driver   |   glGetAttachedShaders (6, 16, [ 2 ], [ 4, 5 ])
    internal |   Regal::Iff::Program::Samplers ()
    driver   |   glGetUniformLocation (6, "rglSampler0") returned -1
    driver   |   glGetUniformLocation (6, "rglSampler1") returned -1
    driver   |   glGetUniformLocation (6, "rglSampler2") returned -1
    driver   |   glGetUniformLocation (6, "rglSampler3") returned -1
    internal |   Regal::Iff::Program::Uniforms ()
    driver   |   glGetUniformLocation (6, "rglNormalMatrix") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewMatrix") returned 7
    driver   |   glGetUniformLocation (6, "rglProjectionMatrix") returned 8
    driver   |   glGetUniformLocation (6, "rglModelViewProjectionMatrix") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix0") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix1") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix2") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix3") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix4") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix5") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix6") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix7") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix8") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix9") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix10") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix11") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix12") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix13") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix14") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix15") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewMatrixInverse") returned -1
    driver   |   glGetUniformLocation (6, "rglProjectionMatrixInverse") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewProjectionMatrixInverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix0Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix1Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix2Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix3Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix4Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix5Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix6Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix7Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix8Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix9Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix10Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix11Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix12Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix13Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix14Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix15Inverse") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewMatrixTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglProjectionMatrixTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewProjectionMatrixTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix0Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix1Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix2Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix3Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix4Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix5Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix6Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix7Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix8Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix9Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix10Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix11Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix12Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix13Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix14Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix15Transpose") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewMatrixInverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglProjectionMatrixInverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglModelViewProjectionMatrixInverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix0InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix1InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix2InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix3InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix4InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix5InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix6InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix7InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix8InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix9InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix10InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix11InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix12InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix13InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix14InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTextureMatrix15InverseTranspose") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor0") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor1") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor2") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor3") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor4") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor5") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor6") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor7") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor8") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor9") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor10") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor11") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor12") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor13") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor14") returned -1
    driver   |   glGetUniformLocation (6, "rglTexEnvColor15") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0ObjS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0ObjT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0ObjR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0ObjQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0EyeS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0EyeT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0EyeR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen0EyeQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1ObjS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1ObjT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1ObjR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1ObjQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1EyeS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1EyeT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1EyeR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen1EyeQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2ObjS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2ObjT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2ObjR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2ObjQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2EyeS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2EyeT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2EyeR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen2EyeQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3ObjS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3ObjT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3ObjR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3ObjQ") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3EyeS") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3EyeT") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3EyeR") returned -1
    driver   |   glGetUniformLocation (6, "rglTexGen3EyeQ") returned -1
    driver   |   glGetUniformLocation (6, "rglLight0[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight1[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight2[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight3[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight4[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight5[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight6[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglLight7[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglMaterialFront") returned -1
    driver   |   glGetUniformLocation (6, "rglMaterialBack") returned -1
    driver   |   glGetUniformLocation (6, "rglLightModelAmbient") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane0") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane1") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane2") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane3") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane4") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane5") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane6") returned -1
    driver   |   glGetUniformLocation (6, "rglClipPlane7") returned -1
    driver   |   glGetUniformLocation (6, "rglFog") returned -1
    driver   |   glGetUniformLocation (6, "rglConstantColor") returned -1
    driver   |   glGetUniformLocation (6, "rglAttrib[0]") returned -1
    driver   |   glGetUniformLocation (6, "rglAlphaRef") returned -1
    driver   |   glUseProgram (0)
    driver   |   glUseProgram (6)
    driver   |   glIsProgram (6) returned GL_TRUE
    driver   |   glGetAttachedShaders (6, 16, [ 2 ], [ 4, 5 ])
    internal |   Regal::Iff::UpdateUniforms 00547ad8
    driver   |   glUniformMatrix4fv (7, 1, GL_FALSE, [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ])
    driver   |   glUniformMatrix4fv (8, 1, GL_FALSE, [ 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1 ])
    app      |   glVertex2f (-0.5, -0.5)
    app      |   glVertex2f (0.5, -0.5)
    app      |   glVertex2f (0.5, 0.5)
    app      |   glVertex2f (-0.5, 0.5)
    app      |   glVertex2f (-0.5, 1.5)
    app      |   glVertex2f (0.5, 1.5)
    app      | glEnd ()
    driver   | glBufferData (GL_ARRAY_BUFFER, 768, [ 000000bf 000000bf 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 0000003f 000000bf 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 0000003f 0000003f 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 000000bf 0000003f 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 000000bf 0000c03f 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 0000003f 0000c03f 00000000 0000803f 0000803f 00000000 00000000 0000803f 00000000 00000000 0000803f 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 0000803f 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 ], GL_DYNAMIC_DRAW)
    internal | Regal::Emu::Quads::glDrawArrays( GL_QUAD_STRIP, 0, 6)
    internal | Regal::Emu::Quads: shadeMode     = GL_SMOOTH
    internal | Regal::Emu::Quads: windingMode   = GL_CCW
    internal | Regal::Emu::Quads: provokeMode   = GL_LAST_VERTEX_CONVENTION
    internal | Regal::Emu::Quads: convention    = false
    internal | Regal::Emu::Quads: frontFaceMode = GL_FILL
    internal | Regal::Emu::Quads: backFaceMode  = GL_FILL
    internal | Regal::Emu::Quads: cullingFaces  = false
    internal | Regal::Emu::Quads: cullFace      = GL_BACK
    internal | Regal::Emu::Quads: drawQuads     = true
    internal | Regal::Emu::Quads: drawLines     = false
    internal | Regal::Emu::Quads: drawPoints    = false
    internal | Regal::Emu::Quads::glDrawArrays glDrawElements(GL_TRIANGLES,12,GL_UNSIGNED_INT, [])
    driver   | glDrawElements (GL_TRIANGLES, 12, GL_UNSIGNED_INT, 00057a80)
    driver   | glBindBuffer (GL_ARRAY_BUFFER, 0)
    driver   | glBindBuffer (GL_ELEMENT_ARRAY_BUFFER, 0)
    driver   | glDisableVertexAttribArray (0)
    driver   | glVertexAttribPointer (0, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (1)
    driver   | glVertexAttribPointer (1, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (2)
    driver   | glVertexAttribPointer (2, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (3)
    driver   | glVertexAttribPointer (3, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (4)
    driver   | glVertexAttribPointer (4, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (5)
    driver   | glVertexAttribPointer (5, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (6)
    driver   | glVertexAttribPointer (6, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    driver   | glDisableVertexAttribArray (7)
    driver   | glVertexAttribPointer (7, 4, GL_FLOAT, GL_FALSE, 0, 00000000)
    
(Originally reported at https://github.com/kripken/emscripten/issues/7867 but here may be better...)

**Comment by gabrielcuvillier** [comment]
The Regal Quads emulation layer seems to not fill any data in the indexbuffer when using QUAD_STRIPS and draws the triangles directly, while it use the indexbuffer with QUADS mode only.

Three possibilities:
- For some reason the "-s FULL_ES2=1" flag have not been enabled when building the port (it should automatically normally). Try to rebuild your project with that flag enabled, because it allows to draw directly without using VBO (Regal expect this)
- Try to tweak the EmuQuads.cpp with the following: update the code at lines 267-276 (QUAD_STRIPS direct draw) with similar code than 329-339 (QUADS with index buffer)

**Comment by claudeha** [comment]
`-s FULL_ES2=1` is enabled afaict by `regal.py`:

    def process_dependencies(settings):
      if settings.USE_REGAL == 1:
        settings.FULL_ES2 = 1

I rebuilt my project with it explicitly added and no change.  Not sure how to explicitly enable it when building the port, if that's what you mean.

Is there documentation somewhere about working on local modifications to a port?  I am quite new to Emscripten.

**Comment by claudeha** [comment]
`-s FULL_ES2=1` is enabled afaict by `regal.py`:

    def process_dependencies(settings):
      if settings.USE_REGAL == 1:
        settings.FULL_ES2 = 1

I rebuilt my project with it explicitly added and no change.  Not sure how to explicitly enable it when building the port, if that's what you mean.

Is there documentation somewhere about working on local modifications to a port?  I am quite new to Emscripten.

**Comment by claudeha** [comment]
thank @kripken got it to work like this

    export EMCC_LOCAL_PORTS="regal=/home/empd/src/regal|regal-version_4"
    cd $HOME
    rm -r .emscripten_cache/asmjs/regal.bc .emscripten_cache/asmjs/ports-builds/regal .emscripten_ports/regal*
    # rebuild my project
